# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'HistoriasDelLaberinto' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HistoriasDelLaberinto
  pod 'Yams'
  pod 'SwiftLint'
  pod 'Kingfisher', '5.5.0'
  pod "Pastel"
end
